/**
 * MNHEME Themes — Diary / Journal Aesthetic
 * ==========================================
 * Each theme is a flat map of CSS custom-property names (without the --)
 * to values.  The ThemeProvider writes them to :root.
 */

export const THEMES = {
  /* ─── 1. Classic Diary ──────────────────────────────── */
  classic: {
    name: 'Classic Diary',
    description: 'Warm cream tones, serif fonts, paper feel',
    vars: {
      '--bg':           '#f5f0e8',
      '--bg2':          '#fffdf7',
      '--bg3':          '#f9f5ed',
      '--surface':      '#ffffff',
      '--border':       '#e0d5c1',
      '--border2':      '#cfc3ab',
      '--accent':       '#8b6914',
      '--accent-dim':   '#c4a95a',
      '--accent-pale':  '#d4bc6a',
      '--accent-bg':    'rgba(139,105,20,0.07)',
      '--accent-bg2':   'rgba(139,105,20,0.04)',
      '--red':          '#c0392b',
      '--blue':         '#2980b9',
      '--amber':        '#d4a017',
      '--text':         '#3d2e1c',
      '--text2':        '#5a4a32',
      '--muted':        '#8c7b62',
      '--faint':        '#c8bda6',
      '--font-heading': "'Playfair Display', 'Georgia', serif",
      '--font-body':    "'Lora', 'Georgia', serif",
      '--font-mono':    "'IBM Plex Mono', 'Courier New', monospace",
      '--sidebar-bg':   '#ede7d9',
      '--sidebar-border': '#d6ccb8',
      '--card-shadow':  '0 1px 4px rgba(61,46,28,0.08), 0 2px 12px rgba(61,46,28,0.04)',
      '--card-radius':  '6px',
      '--selection-bg': 'rgba(139,105,20,0.15)',
      '--scrollbar-thumb': '#c8bda6',
      '--scrollbar-track': '#f5f0e8',
      '--input-bg':     '#faf7f0',
      '--btn-text':     '#fffdf7',
      '--overlay-bg':   'rgba(61,46,28,0.4)',
      '--transition-speed': '0.3s',
    },
  },

  /* ─── 2. Moonlight Journal ──────────────────────────── */
  moonlight: {
    name: 'Moonlight Journal',
    description: 'Dark mode with soft blues and purples',
    vars: {
      '--bg':           '#131825',
      '--bg2':          '#1a2035',
      '--bg3':          '#1e2540',
      '--surface':      '#212845',
      '--border':       '#2a3355',
      '--border2':      '#354070',
      '--accent':       '#9b8adb',
      '--accent-dim':   '#6b5eaa',
      '--accent-pale':  '#b8adea',
      '--accent-bg':    'rgba(155,138,219,0.1)',
      '--accent-bg2':   'rgba(155,138,219,0.05)',
      '--red':          '#e57373',
      '--blue':         '#7dc4e8',
      '--amber':        '#f0c674',
      '--text':         '#d4d4e8',
      '--text2':        '#b0b0cc',
      '--muted':        '#6e7099',
      '--faint':        '#2e3455',
      '--font-heading': "'Playfair Display', 'Georgia', serif",
      '--font-body':    "'Lora', 'Georgia', serif",
      '--font-mono':    "'IBM Plex Mono', 'Courier New', monospace",
      '--sidebar-bg':   '#161c2e',
      '--sidebar-border': '#252d48',
      '--card-shadow':  '0 1px 6px rgba(0,0,0,0.3), 0 2px 16px rgba(0,0,0,0.15)',
      '--card-radius':  '6px',
      '--selection-bg': 'rgba(155,138,219,0.2)',
      '--scrollbar-thumb': '#3a4468',
      '--scrollbar-track': '#131825',
      '--input-bg':     '#171e30',
      '--btn-text':     '#131825',
      '--overlay-bg':   'rgba(10,14,25,0.6)',
      '--transition-speed': '0.3s',
    },
  },

  /* ─── 3. Vintage Notebook ───────────────────────────── */
  vintage: {
    name: 'Vintage Notebook',
    description: 'Aged paper, earthy tones, nostalgic feel',
    vars: {
      '--bg':           '#ece3d0',
      '--bg2':          '#f7f0e0',
      '--bg3':          '#f0e9d8',
      '--surface':      '#faf5e8',
      '--border':       '#c9b998',
      '--border2':      '#b5a37e',
      '--accent':       '#9c5e2e',
      '--accent-dim':   '#c48a5a',
      '--accent-pale':  '#d4a070',
      '--accent-bg':    'rgba(156,94,46,0.08)',
      '--accent-bg2':   'rgba(156,94,46,0.04)',
      '--red':          '#a94442',
      '--blue':         '#4a7c8f',
      '--amber':        '#b8860b',
      '--text':         '#42331e',
      '--text2':        '#5e4a30',
      '--muted':        '#8a7558',
      '--faint':        '#c8b898',
      '--font-heading': "'Playfair Display', 'Georgia', serif",
      '--font-body':    "'Lora', 'Georgia', serif",
      '--font-mono':    "'IBM Plex Mono', 'Courier New', monospace",
      '--sidebar-bg':   '#e0d5be',
      '--sidebar-border': '#c8b898',
      '--card-shadow':  '0 1px 4px rgba(66,51,30,0.1), 0 3px 14px rgba(66,51,30,0.06)',
      '--card-radius':  '4px',
      '--selection-bg': 'rgba(156,94,46,0.15)',
      '--scrollbar-thumb': '#c0ad8a',
      '--scrollbar-track': '#ece3d0',
      '--input-bg':     '#f2ead6',
      '--btn-text':     '#faf5e8',
      '--overlay-bg':   'rgba(66,51,30,0.4)',
      '--transition-speed': '0.3s',
    },
  },

  /* ─── 4. Minimalist Zen ─────────────────────────────── */
  zen: {
    name: 'Minimalist Zen',
    description: 'Clean whites, subtle grays, calm teal accent',
    vars: {
      '--bg':           '#fafafa',
      '--bg2':          '#ffffff',
      '--bg3':          '#f5f5f5',
      '--surface':      '#ffffff',
      '--border':       '#e8e8e8',
      '--border2':      '#d4d4d4',
      '--accent':       '#3d8b8b',
      '--accent-dim':   '#66aaaa',
      '--accent-pale':  '#80c0c0',
      '--accent-bg':    'rgba(61,139,139,0.07)',
      '--accent-bg2':   'rgba(61,139,139,0.03)',
      '--red':          '#d4574e',
      '--blue':         '#5087b0',
      '--amber':        '#c59530',
      '--text':         '#2c2c2c',
      '--text2':        '#4a4a4a',
      '--muted':        '#8c8c8c',
      '--faint':        '#d4d4d4',
      '--font-heading': "'Inter', 'Helvetica Neue', sans-serif",
      '--font-body':    "'Inter', 'Helvetica Neue', sans-serif",
      '--font-mono':    "'IBM Plex Mono', 'Courier New', monospace",
      '--sidebar-bg':   '#f2f2f2',
      '--sidebar-border': '#e0e0e0',
      '--card-shadow':  '0 1px 3px rgba(0,0,0,0.06), 0 1px 8px rgba(0,0,0,0.03)',
      '--card-radius':  '8px',
      '--selection-bg': 'rgba(61,139,139,0.12)',
      '--scrollbar-thumb': '#cccccc',
      '--scrollbar-track': '#fafafa',
      '--input-bg':     '#f8f8f8',
      '--btn-text':     '#ffffff',
      '--overlay-bg':   'rgba(44,44,44,0.3)',
      '--transition-speed': '0.3s',
    },
  },

  /* ─── 5. Garden Journal ─────────────────────────────── */
  garden: {
    name: 'Garden Journal',
    description: 'Soft sage and mint, botanical vibes',
    vars: {
      '--bg':           '#eef3ec',
      '--bg2':          '#f7faf5',
      '--bg3':          '#f0f5ee',
      '--surface':      '#fcfdf9',
      '--border':       '#c8d8c2',
      '--border2':      '#b0c4a8',
      '--accent':       '#4a7c4a',
      '--accent-dim':   '#6a9e6a',
      '--accent-pale':  '#80b880',
      '--accent-bg':    'rgba(74,124,74,0.08)',
      '--accent-bg2':   'rgba(74,124,74,0.04)',
      '--red':          '#c0392b',
      '--blue':         '#3f7cac',
      '--amber':        '#b8860b',
      '--text':         '#2c3a28',
      '--text2':        '#3e5038',
      '--muted':        '#6b8064',
      '--faint':        '#b8ccb2',
      '--font-heading': "'Playfair Display', 'Georgia', serif",
      '--font-body':    "'Lora', 'Georgia', serif",
      '--font-mono':    "'IBM Plex Mono', 'Courier New', monospace",
      '--sidebar-bg':   '#e2ecde',
      '--sidebar-border': '#c8d8c2',
      '--card-shadow':  '0 1px 4px rgba(44,58,40,0.08), 0 2px 12px rgba(44,58,40,0.04)',
      '--card-radius':  '6px',
      '--selection-bg': 'rgba(74,124,74,0.15)',
      '--scrollbar-thumb': '#b0c4a8',
      '--scrollbar-track': '#eef3ec',
      '--input-bg':     '#f4f8f2',
      '--btn-text':     '#f7faf5',
      '--overlay-bg':   'rgba(44,58,40,0.35)',
      '--transition-speed': '0.3s',
    },
  },
};

export const THEME_IDS = Object.keys(THEMES);
export const DEFAULT_THEME = 'classic';
